### ISSUE TITLE
Fix CI: tui-term/tui-ubuf compilation errors cause raco pkg install to fail

### ISSUE THREAD

**Issue by coinerd** [coinerd/q#39]
## Problem

CI has been red since commit `ada36f5` (Wave 1 of v0.4.0) when `tui-term` and `tui-ubuf` were added as **required** deps in `info.rkt`.

`tui-term` does not compile on Racket 8.10 — it uses `vector-extend` (unbound identifier) and `terminal-pending-winch?` (missing from `#%terminal`). These are features from newer Racket versions.

```
raco setup: error: during making for <pkgs>/tui-term
  gen-buf-reader.rkt:56:27: vector-extend: unbound identifier
  tty-input-port.rkt:3:18: only-in: identifier terminal-pending-winch? not included
raco pkg install: packages installed, although setup reported errors
Error: Process completed with exit code 1.
```

## Root Cause

`tui-term` and `tui-ubuf` are **already used via `dynamic-require` with fallback stubs** — the TUI degrades gracefully without them. They were correctly optional before v0.4.0. Making them required deps was wrong because:
1. The packages do not compile on Racket 8.10
2. The code already handles their absence gracefully
3. `raco pkg install` exits 1 when setup reports errors, even though packages are installed

### 1. Make tui-term and tui-ubuf optional in `info.rkt`

Move from `deps` to a comment documenting them as optional:

```racket
(define deps '("base"))

;; Optional — dynamically-required with fallback stubs.
;; Install separately for full TUI: raco pkg install tui-term tui-ubuf
;; These packages do NOT compile on Racket 8.10 (upstream bugs).
```

### 2. Update CI to install optional deps gracefully

```yaml
- name: Install dependencies
  run: |
    raco pkg install --auto --batch
    raco pkg install --auto --batch tui-term tui-ubuf 2>/dev/null || true
```

The `|| true` ensures CI does not fail on tui-term compilation errors.

## Acceptance
- [ ] CI passes green on `main`
- [ ] `raco pkg install --auto --batch` exits 0 on fresh Racket 8.10
- [ ] TUI still works with fallback stubs
- [ ] All tests pass (2466+)
- [ ] docs/install.md documents optional TUI packages

**Comment by coinerd** [comment]
Fixed in e0dae73.

Root cause: tui-term uses `vector-extend` and `terminal-pending-winch?` which do not exist in Racket 8.10. When added as required deps, `raco pkg install` exits 1.

Fix: Removed from required deps. Both packages are dynamically-required with fallback stubs — TUI works without them.

CI: Install step now runs `raco pkg install --auto --batch` (required only) followed by optional install with `|| true`.

2466 tests passing, 0 failures. Version bumped to 0.4.1.
